### ISSUE TITLE
Crash on world generation

### ISSUE THREAD

**Issue by ParzivalWolfram** [McJty/LostCities#329]
Minecraft 1.16.3
Forge 34.1.42
Lost Cities 1.16-4.0.1-alpha

Given crash reason:
```
The game crashed whilst starting integrated server
Error: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.compareNamespaced(Lnet/minecraft/util/ResourceLocation;)I
Exit Code: 255
```
[Full crash log.](https://github.com/McJtyMods/LostCities/files/5528048/crash-2020-11-11_21.17.03-client.txt)

**Comment by ParzivalWolfram** [comment]
apparently Forge is just busted this time. neat. this is why you target stable builds and not latest, kids.

**Comment by ParzivalWolfram** [comment]
since no one seems to know what versions work with this mod (or at all) i'm gonna start a list of what i try and how it dies here:
34.1.0: Crashes (mod uses method that isn't implemented yet)
34.1.18: Crashes (mod uses method that isn't implemented yet)
34.1.21: Crashes (Forge is busted)
34.1.24: Crashes (Forge is busted)
34.1.30: Crashes (Forge is busted)
34.1.42: Crashes (Forge is busted)

Notes:
"Forge is busted" means that, for any combo of mods, the following error occurs:
```
The game crashed whilst starting integrated server
Error: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.compareNamespaced(Lnet/minecraft/util/ResourceLocation;)I
Exit Code: 255
```

For "mod uses method that isn't implemented yet", I mean Forge generally works on its own or with several other mods, but this happens with this mod regardless of whether or not it's alone:
```
The game crashed whilst mouseclicked event handler
Error: java.lang.NoClassDefFoundError: net/minecraftforge/common/BiomeDictionary$Type
Exit Code: 255
``` 

(though the location for both can change depending on if you're making a world or loading a new one)

**Comment by ParzivalWolfram** [comment]
Addendum: Lost Cities only works on 34.1.42 IF NO OTHER MODS ARE PRESENT. Not even Optifine. Literally nothing else can load but Lost Cities and Forge or it'll die if you try to init the game's engine. I got stuck at 52% map generation, though.

**Comment by McJty** [comment]
Die how? What happens if you add any other mod? Can you show logs?

**Comment by ParzivalWolfram** [comment]
"Die how?" and "What happens if you add any other mod?" are covered above. As for logs, I have several.
[crash-2020-11-11_21.13.32-client.txt](https://github.com/McJtyMods/LostCities/files/5532286/crash-2020-11-11_21.13.32-client.txt)
[crash-2020-11-11_21.17.03-client.txt](https://github.com/McJtyMods/LostCities/files/5532287/crash-2020-11-11_21.17.03-client.txt)
[crash-2020-11-11_21.41.49-client.txt](https://github.com/McJtyMods/LostCities/files/5532288/crash-2020-11-11_21.41.49-client.txt)
[crash-2020-11-11_21.48.23-client.txt](https://github.com/McJtyMods/LostCities/files/5532289/crash-2020-11-11_21.48.23-client.txt)
[crash-2020-11-11_21.56.03-client.txt](https://github.com/McJtyMods/LostCities/files/5532290/crash-2020-11-11_21.56.03-client.txt)
[crash-2020-11-11_22.00.29-client.txt](https://github.com/McJtyMods/LostCities/files/5532291/crash-2020-11-11_22.00.29-client.txt)
[crash-2020-11-11_22.03.20-client.txt](https://github.com/McJtyMods/LostCities/files/5532292/crash-2020-11-11_22.03.20-client.txt)
[crash-2020-11-11_22.05.04-client.txt](https://github.com/McJtyMods/LostCities/files/5532293/crash-2020-11-11_22.05.04-client.txt)
[crash-2020-11-11_22.52.02-client.txt](https://github.com/McJtyMods/LostCities/files/5532294/crash-2020-11-11_22.52.02-client.txt)
[crash-2020-11-11_22.53.05-client.txt](https://github.com/McJtyMods/LostCities/files/5532295/crash-2020-11-11_22.53.05-client.txt)
[crash-2020-11-11_22.57.01-client.txt](https://github.com/McJtyMods/LostCities/files/5532296/crash-2020-11-11_22.57.01-client.txt)

**Comment by McJty** [comment]
Ok, some of those crashlogs have nothing to do with Lost Cities. With others I see you're using a version of Forge that's too old. I'm only interested in a crashlog that is for a recent forge and related to Lost Cities. You have anything like that?

**Comment by ParzivalWolfram** [comment]
several of those had no mods other than lost cities used and you do not
have a specific forge version listed anywhere. you're also not targeting
the stable build (what they call "recommended") so uh... what minimum
version you want and did you know optifine and other fairly-common mods
kill your mod?

**Comment by McJty** [comment]
Just use latest please. The stable/recommended build is not something you should target in my opinion. It has too many bugs. Forge is too slow in updating to their stable/recommended so I never target that.

As for optifine, if that kills my mod there is nothing I can do. That's on their side to fix. And what other fairly common mods kill my mod anyway?

So for latest forge I need a crashlog where Lost Cities is crashing

**Comment by ParzivalWolfram** [comment]
LostCities makes the game crash if any of the following mods are also present:
Optifine
Xaero's Minimap/World Map
Clumps
FastFurnace/FastWorkbench
TrashSlot
JustEnoughItems (sometimes works, sometimes not)

Just generated on 34.1.42, where Forge dies only if your mod is included among the rest of my shit:
[crash-2020-11-14_02.02.59-client.txt](https://github.com/McJtyMods/LostCities/files/5540365/crash-2020-11-14_02.02.59-client.txt)

**Comment by McJty** [comment]
Well no clue. It doesn't crash in my mod so I have nothing that I can fix and I have no clue why Lost Cities would cause this. BTW, I myself am using JEI constantly and never got a problem with that. In addition at this moment nobody else reported any problems with Lost Cities on 1.16 (and people have been using it) so I'm totally out of clues

**Comment by ParzivalWolfram** [comment]
I'm running OpenJRE 8u272-b10-1 on Linux, which probably differs from you.
OpenJRE 8 is Java 8 with some varying additional fixes, and i'm on Linux,
and either of those may or may not be the issue. I can also send you all of
my mods (or my entire .minecraft folder, really) if you'd like them to test
with.

**Comment by ParzivalWolfram** [comment]
I can also try other Java versions if you want as well. I have open-source versions of Java 8, 11, 13, 14, and 15 I can test with.
