### ISSUE TITLE
Does not work on 1.10.2

### ISSUE THREAD

**Issue by wassaily** [McJty/LostCities#70]
Please make a stable 1.10.2 version, I'd like to have this mod as a dimension on my server. I've tried different profiles on both singleplayer and multiplayer, it always freezes or crashes on entering. I've even tried 1.11.2 with no other mods installed and it still crashed.  I can generate the world on my 1.10.2 server but here's what happens when you try to enter:

[16:42:31] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$NeighborNotifyEvent@4c6023f5:
java.lang.NoSuchMethodError: mcjty.lib.tools.EntityTools.setSpawnerEntity(Lnet/minecraft/world/World;Lnet/minecraft/tileentity/TileEntityMobSpawner;Lnet/minecraft/util/ResourceLocation;Ljava/lang/String;)V
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.generateLootSpawners(LostCityChunkGenerator.java:363) ~[LostCityChunkGenerator.class:?]
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.func_185931_b(LostCityChunkGenerator.java:526) ~[LostCityChunkGenerator.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000) ~[asv.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964) ~[asv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) ~[lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:842) ~[aid.class:?]
	at net.olafkeijsers.fastleafdecay.LeafUpdateEventHandler.UpdateNeighbour(LeafUpdateEventHandler.java:29) ~[LeafUpdateEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_344_LeafUpdateEventHandler_UpdateNeighbour_NeighborNotifyEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onNeighborNotify(ForgeEventFactory.java:158) [ForgeEventFactory.class:?]
	at net.minecraft.world.World.func_175685_c(World.java:462) [aid.class:?]
	at net.minecraft.world.World.func_175722_b(World.java:423) [aid.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368) [aid.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:349) [aid.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:408) [aid.class:?]
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.createVineStrip(LostCityChunkGenerator.java:327) [LostCityChunkGenerator.class:?]
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.generateVines(LostCityChunkGenerator.java:290) [LostCityChunkGenerator.class:?]
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.func_185931_b(LostCityChunkGenerator.java:525) [LostCityChunkGenerator.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000) [asv.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964) [asv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) [lr.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) [lx.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) [ly.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by McJty** [comment]
Do you have the correct version of compatlayer?

**Comment by wassaily** [comment]
I have 1.6, is that the correct one?

**Comment by McJty** [comment]
1.6 what? Can you give the full filename?

**Comment by wassaily** [comment]
compatlayer-1.10-0.1.6

**Comment by McJty** [comment]
Why are you using such an old version? The last release is compatlayer-1.10-0.3.0.jar

This is most likely causing your problem

**Comment by wassaily** [comment]
That's the version Forge said I need when I tried the mod for the first time so I never questioned it. It doesn't say anywhere in the mod description that you need this or what version, you could put that in so people don't have a problem like this anymore.

Downloaded the newest compatlayer and it works just fine, thanks for such a quick response and solution.
